# Generated by Django 5.1.3 on 2025-06-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('poblacion', models.IntegerField(null=True)),
                ('tasa_de_vulnerabilidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_fundacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
