# Generated by Django 5.1.3 on 2025-06-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisComunas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
