# Generated by Django 5.1.3 on 2025-06-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MisComunas', '0002_alter_comunas_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comunas',
            new_name='Comuna',
        ),
    ]
